=== PNNL-Comp-Mass-Spec/Parameter-File-Editor/ParamFileEditor/Sheet1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="Sheet1"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="Sheet1">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="DMS_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Value_Type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SQ_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Internal_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== PNNL-Comp-Mass-Spec/Parameter-File-Editor/ParamFileEditor/Sheet1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Sheet1.xsd">
<Sheet1>
<DMS_Name>SQ_Param_File_Desc</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>DMS_Description</SQ_Name>
<Internal_Name>Description</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Database_1</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>first_database_name</SQ_Name>
<Internal_Name>DefaultFASTAPath</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Database_2</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>second_database_name</SQ_Name>
<Internal_Name>DefaultFASTAPath2</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Peptide_Mass_Tolerance</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>peptide_mass_tolerance</SQ_Name>
<Internal_Name>PeptideMassTolerance</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Create_Output_Files</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>create_output_files</SQ_Name>
<Internal_Name>CreateOutputFIles</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_Use_A</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>Use_a_Ions</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_Use_B</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>Use_b_Ions</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_Use_Y</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>Use_y_Ions</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_a_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>a_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_b_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>b_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_c_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>c_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_d_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>d_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_v_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>v_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_w_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>w_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_x_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>x_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_y_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>y_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ions_z_Weight</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_series</SQ_Name>
<Internal_Name>z_Ion_Weighting</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod1_AAList</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod1_AAList</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod2_AAList</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod2_AAList</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod3_AAList</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod3_AAList</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod1_Mass</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod1_MassDiff</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod2_Mass</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod2_MassDiff</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Dyn_Mod3_Mass</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>diff_search_options</SQ_Name>
<Internal_Name>Dyn_Mod3_MassDiff</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Max_Dyn_Mods</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>max_num_differential_AA_per_mod</SQ_Name>
<Internal_Name>MaximumNumAAPerDynMod</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Frag_Ion_Tolerance</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>fragment_ion_tolerance</SQ_Name>
<Internal_Name>FragmentIonTolerance</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Num_Output_Lines</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>num_output_lines</SQ_Name>
<Internal_Name>NumberOfOutputLines</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Num_Desc_Lines</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>num_description_lines</SQ_Name>
<Internal_Name>NumberOfDescriptionLines</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Num_Results_Used</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>num_results</SQ_Name>
<Internal_Name>NumberOfResultsToProcess</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Show_Fragments</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>show_fragment_ions</SQ_Name>
<Internal_Name>ShowFragmentIons</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Print_Dup_Refs</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>print_duplicate_references</SQ_Name>
<Internal_Name>PrintDuplicateReferences</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Enzyme_Num</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>enzyme_number</SQ_Name>
<Internal_Name>SelectedEnzymeIndex</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Nuc_Reading_Frame</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>nucleotide_reading_frame</SQ_Name>
<Internal_Name>SelectedNucReadingFrame</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Parent_Mass_Type</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>mass_type_parent</SQ_Name>
<Internal_Name>ParentMassType</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Fragment_Mass_Type</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>mass_type_fragment</SQ_Name>
<Internal_Name>FragmentMassType</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Rem_Precursor_Peak</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>remove_precursor_peak</SQ_Name>
<Internal_Name>RemovePrecursorPeak</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Ion_Cutoff_Value</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>ion_cutoff_percentage</SQ_Name>
<Internal_Name>IonCutoffPercentage</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Max_Num_IC_Sites</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>max_num_internal_cleavage_sites</SQ_Name>
<Internal_Name>MaximumNumberMissedCleavages</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Min_Mass_To_Use</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>protein_mass_filter</SQ_Name>
<Internal_Name>MinimumProteinMassToSearch</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Max_Mass_To_Use</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>protein_mass_filter</SQ_Name>
<Internal_Name>MaximumProteinMassToSearch</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Match_Peak_Count</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>match_peak_count</SQ_Name>
<Internal_Name>NumberOfDetectedPeaksToMatch</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Match_Peak_Errors</DMS_Name>
<Value_Type>Integer</Value_Type>
<SQ_Name>match_peak_allowed_error</SQ_Name>
<Internal_Name>NumberOfAllowedDetectedPeakErrors</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Match_Peak_Tolerance</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>match_peak_tolerance</SQ_Name>
<Internal_Name>MatchedPeakMassTolerance</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_AA_In_Uppercase</DMS_Name>
<Value_Type>Boolean</Value_Type>
<SQ_Name>residues_in_upper_case</SQ_Name>
<Internal_Name>AminoAcidsAllUpperCase</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Partial_Sequence</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>partial_sequence</SQ_Name>
<Internal_Name>PartialSequenceToMatch</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Seq_Header_Filter</DMS_Name>
<Value_Type>String</Value_Type>
<SQ_Name>sequence_header_filter</SQ_Name>
<Internal_Name>SequenceHeaderInfoToFilter</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_CT_Pep</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_Cterm_peptide</SQ_Name>
<Internal_Name>CtermPeptide</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_CT_Prot</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_Cterm_protein</SQ_Name>
<Internal_Name>CtermProtein</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_NT_Pep</DMS_Name>
<Value_Type>Single
Single</Value_Type>
<SQ_Name>add_Nterm_peptide</SQ_Name>
<Internal_Name>NtermPeptide</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_NT_Prot</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_Nterm_protein</SQ_Name>
<Internal_Name>NtermProtein</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_G_Gly</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_G_Glycine</SQ_Name>
<Internal_Name>G_Glycine</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_A_Ala</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_A_Alanine</SQ_Name>
<Internal_Name>A_Alanine</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_S_Ser</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_S_Serine</SQ_Name>
<Internal_Name>S_Serine</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_P_Pro</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_P_Proline</SQ_Name>
<Internal_Name>P_Proline</Internal_Name>
</Sheet1>
<Sheet1>
<DMS_Name>SQ_Stat_V_Val</DMS_Name>
<Value_Type>Single</Value_Type>
<SQ_Name>add_V_Valine</SQ_Name>
